name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: eslint review
#        uses: reviewdog/action-eslint@v1
#        with:
#          reporter: github-pr-review
#          eslint_flags: '{src,apps,libs,test}/**/*.ts --fix'
#          fail_on_error: 'true'
        run: npm run lint | reviewdog -reporter=github-pr-review
