name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: '{src,apps,libs,test}/**/*.ts'
          level: error
          fail_on_error: 'true'
        # 以下のアクションがないと、GitHub Actions が正常に終了してしまい、Pull Request に指摘コメントが入らなかったため、追加した。
      - name: eslint
        run: npm run lint
